name: Build and Deploy Image to AWS ECR using GitHub Actions

on:
  push:
    tags:
      - "v*.*.*"

env:
  AWS_REGION: ap-southeast-1

jobs: 

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

  deploy:
    name: Deploy to AWS ECR
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Test environment variable
        run: echo ${{ env.RELEASE_VERSION }}
