name: Build and Deploy Image to AWS ECR using GitHub Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs: 
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set environment variable
      run: echo "Hello World"